### PR TITLE
Updates function to be able to collapse and expende the feedback button

### LINKED ISSUE #8: contact us button hides important controls on maps
Oin thematic maps, such as https://opendevelopmentmekong.net/maps/aqueduct-atlas/, the **Contact us** button blocks important functionality.

screenshot from 2017-03-22 09-17-43

### PR DESCRIPTION
**Pull request by Huyeng**
Fixes #8

### CODE REVIEW

**Comment by acorbi** [comment]
@Huyeng I have just tested this on PP. I can reproduce 2 problems:

### On firefox 52.0.1:

 The button for showing the box does not appear after I click on the button to hide it. See screenshots below:

screenshot from 2017-03-27 10-22-18
screenshot from 2017-03-27 10-22-35

## On chrome Version 57.0.2987.110

The khmer text is not laying out properly on the button , but outside of it.

screenshot from 2017-03-27 10-28-09

Can you reproduce this errors?

**Comment by acorbi** [comment]
@Huyeng this is relevant. The images seem to be referenced from cambodia.odm.web which belongs to your local machine

screenshot from 2017-03-27 12-46-29

**Comment by Huyeng** [comment]
They are looking fine on  my Localhost. Sharing screenshot form team member who using the same version as yours: 
screenshot_1
screenshot_2
screenshot_3

**Comment by acorbi** [comment]
Ok, the problem with the visibility of the button seems to be fixed, however there is an alignment issue with the button:

screenshot from 2017-03-27 13-09-32

I would recomend to use the following css code:

```
.hide-feedbackbuttom {
    position: absolute;
    left: 18px;
    bottom: 0px;
    cursor: pointer;
}
```

I believe that should work with all browsers and resolutions. Can you please check?

**Comment by acorbi** [comment]
On https://pp.opendevelopmentmekong.net/map-explorer

screenshot from 2017-03-27 13-29-21

**Pull request merged**
