### PR TITLE
Impl 35

### LINKED ISSUE #35: Suggest to add the captcha before submit to prevent spam
Sometimes, there are some emails have been sent that are considered as spam. To prevent the spam, the captcha need to add.

### PR DESCRIPTION
**Pull request by Huyeng**
Add captcha
Fixes #35

### CODE REVIEW

**Comment by Huyeng** [comment]
ok. I added these lines into the wp-odm_user_feedback/composer.json

`"repositories": [
				{
            "type": "vcs",
            "url": "https://github.com/claviska/simple-php-captcha",
				"autoload": {
				        "files": ["simple-php-captcha.php"]
				  }
        }
		],`

And added this request in wp-odm_user_feedback.php
`require_once 'vendor/autoload.php';`

However, the error message appeared:
Fatal error: Call to undefined function simple_php_captcha();
Did i add autoload incorrectly?

**Comment by acorbi** [comment]
@Huyeng I pushed some code changes:

1. The way the dependency is added to the composer.json file:

```
"require": {
      "abeautifulsite/simple-php-captcha": "*"
    }
```

2. The way the simple-php-captcha.php file is included:

```
include_once plugin_dir_path(__FILE__).'vendor/abeautifulsite/simple-php-captcha/simple-php-captcha.php';
```

Read my comment on https://github.com/claviska/simple-php-captcha/pull/25, the developer of the library needs to update the file on https://packagist.org/packages/abeautifulsite/simple-php-captcha in order for autoload to work. We should keep an eye on that PR I linked above in order to remove the `include_once` once its done.

Please test and merge if it works

**Comment by Huyeng** [comment]
How did you know to add the "abeautifulsite/simple-php-captcha" into the composer's require?

**Comment by acorbi** [comment]
Composer packages are managed on http://packagist.org/ you can search for the packages name there

**Comment by Huyeng** [comment]
I see. Thanks. Merging now.

**Pull request merged**
